-- :help options
--local options = {
	-- autochdir = true, -- Automatically change the current directory based on current file.
	-- autoindent = false,
	-- autoread = true,
	-- buflisted = true,
	-- cindent = true,
	-- cinkeys = "o,O", -- Keys that trigger auto-indent
	-- clipboard = "unnamedplus",
	-- cmdheight = 2,
	-- completeopt = "menuone,noinsert",
	-- conceallevel = 0,
	-- confirm = true,
	-- cursorline = true,
	-- debug = "msg",
	-- digraph = false,
	-- display = "uhex",
	-- expandtab = false,
	-- fileencoding = "utf-8",
	-- formatoptions = "tcnqjw",
	-- hlsearch = true,
	-- ignorecase = true,
	-- indentexpr = "",
	-- matchpairs = "(:),{:},[:],<:>",
	-- mouse = "a",
	-- number = true,
	-- relativenumber = false,
	-- scrolloff = 8,
	-- shiftwidth = 2,
	-- showtabline = 2,
	-- sidescrolloff = 8,
	-- signcolumn = "yes",
	-- smartcase = false,
	-- smartindent = false,
	-- splitbelow = true,
	-- splitright = true,
	-- tabstop = 2,
	-- updatetime = 300,
	-- wrap = true,
	-- scrolloff = 0,
	-- winbar = "",
--}

--for k, v in pairs(options) do
--  vim.opt[k] = v
--end

-- Keep visual after indenting
--vim.api.nvim_set_keymap('v', '<', '<gv', { noremap = true, silent = true })
--vim.api.nvim_set_keymap('v', '>', '>gv', { noremap = true, silent = true })


-- vim.api.nvim_set_keymap('n', '<Esc>', ':noh<CR>', { noremap = true, silent = true })

